
services: 
  nginx: 
    image: nginx 
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    ports: 
     - "8082:80"
    restart: always
    networks:
      - self_healing_net
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command: [ "-nginx.scrape-uri", "http://nginx/stub_status" ]
    ports:
      - "9113:9113"
    networks:
      - self_healing_net

  prometheus: 
    image: prom/prometheus
    container_name: prometheus
    volumes: 
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
     - ./rules.yml:/etc/prometheus/rules.yml
     - prometheus_data:/prometheus
    ports: 
     - "9090:9090"
    networks:
      - self_healing_net

  alertmanager: 
    image: prom/alertmanager
    container_name: alertmanager
    volumes: 
     - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
     - "9093:9093"
    networks:
      - self_healing_net
  
  webhook: 
    build: ./webhook
    container_name: webhook
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root  

    ports:
     - "5001:5001"
    networks:
     - self_healing_net

volumes:
  prometheus_data: 
networks:
  self_healing_net:
    driver: bridge